### ISSUE TITLE
Filtering events is throwing errors

### ISSUE THREAD

**Issue by martyphee** [deliveroo/routemaster-client-ex#68]
```
drain Routemaster.Drains.Notify,
        listener: PaymentsGatewayWeb.Sinks.EventsSink,
        only: ["llamas", "hedgehogs"]
```

```
defp select(events, {:only, target}) do
    Enum.filter(events, &match(&1.topic, target))
  end
```

```
[error] Task #PID<0.492.0> started from #PID<0.487.0> terminating
** (KeyError) key :topic not found in: %{"t" => 1502651876, "topic" => "hedgehogs", "type" => "update", "url" => "http://localhost:4000/hedgehogs/2"}
    (routemaster) lib/routemaster/drain/drains/notify.ex:119: anonymous fn/2 in Routemaster.Drains.Notify.select/2
    (elixir) lib/enum.ex:2872: Enum.filter_list/2
    (routemaster) lib/routemaster/drain/drains/notify.ex:100: Routemaster.Drains.Notify.call/2
    (payments_gateway_web) lib/payments_gateway_web/drain.ex:1: PaymentsGatewayWeb.Drain._start_async_drains/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.27996008/0 in PaymentsGatewayWeb.Drain.start_async_drains/2>
    Args: []
```

**Comment by tompave-roo** [comment]
This is because the Endpoint in `endpoint.ex` is already parsing the body with the basic JSON parser, which converts the event JSON in the body to simple maps. When the client's parser gets to do its job, the body has already been parsed and it no-op's. I'll add something to the readme to make it clear that you can't have two parsers.

**Comment by tompave-roo** [comment]
In the meantime, here you can find an example of how to solve the problem: https://github.com/tompave/routemaster_client_ex_demo/commit/50190d9be7c82a66717a83f0869ef2a0b6bb1853

**Comment by tompave** [comment]
PR with the extra docs:
https://github.com/deliveroo/routemaster-client-ex/pull/70

I think we should still try to solve the problem by making the parser more flexible. e.g. if the body has already been parsed, do the right thing and try to cast the maps to structs, then proceeed. I've got a branch for that.

**Comment by tompave** [comment]
I've solved the problem by making the parser more flexible: https://github.com/deliveroo/routemaster-client-ex/pull/71

No need for special configuration. Closing the other PR.

**Comment by tompave** [comment]
Fixed
